blank_issues_enabled: true
contact_links:
  - name: New ObjMatrix ticket
    url: https://git.nil.im/ObjFW/ObjMatrix/issues/new
    about:
      Please use this to create a new ticket. You can also report issues on
      GitHub, but this is preferred.
  - name: Existing ObjMatrix tickets
    url: https://git.nil.im/ObjFW/ObjFW/issues
    about: Please use this to look for existing tickets.
  - name: ObjFW Matrix Room
    url: https://matrix.to/#/%23objfw:nil.im
    about: Please use this for interactive questions and support.
