blank_issues_enabled: true
contact_links:
  - name: New ObjMatrix ticket
    url: https://fl.nil.im/objmatrix/tktnew
    about:
      Please use this to create a new ticket. You can also report issues on
      GitHub, but this is preferred.
  - name: Existing ObjMatrix tickets
    url: https://fl.nil.im/objmatrix/reportlist
    about: Please use this to look for existing tickets.
  - name: ObjMatrix Forum
    url: https://fl.nil.im/objmatrix/forum
    about: Please use this if you have questions or want support.
  - name: ObjFW Matrix Room
    url: https://matrix.to/#/%23objfw:nil.im
    about: Please use this for interactive questions and support.
